closed_loop_controller:
  ros__parameters:
    use_sim_time: false
    require_navigation_enable: true
    navigation_enabled_topic: /scan/navigation_enabled
    time_forward: 0.5
    heading_error_threshold: 0.6
    kp_pos: 0.5
    kp_yaw: 1.0
    max_vx: 0.50
    max_vy: 0.08
    max_vyaw: 0.20
    finish_dist: 0.20
